In [10]:
import numpy as np

In [28]:
arr = np.random.randint(0, 100, size=(4, 5))
print(f"Исходный массив:\n{arr}\n")

Исходный массив:
[[94 18 53 37 48]
 [48 83 10 52 23]
 [ 1  7 23 44 58]
 [42 39  6 77 28]]



In [29]:
arr1, arr2 = np.split(arr, 2)
print(f"Первый массив:\n{arr1}\n")
print(f"Второй массив:\n{arr2}\n")

Первый массив:
[[94 18 53 37 48]
 [48 83 10 52 23]]

Второй массив:
[[ 1  7 23 44 58]
 [42 39  6 77 28]]



In [32]:
values = (arr2 == 6)
print(f"Значения, равные 6, в первом массиве:\n{values}\n")

Значения, равные 6, в первом массиве:
[[False False False False False]
 [False False  True False False]]



In [33]:
count = np.sum(values)
print(f"Количество найденных элементов: {count}")


Количество найденных элементов: 1


In [ ]:
import pandas as pd
import numpy as np

In [39]:
s = pd.Series(np.random.randint(0, 100, size=10))
print(f"Объект Series:\n{s}\n")

Объект Series:
0    63
1    79
2    24
3    95
4    35
5     0
6    58
7    63
8    43
9     5
dtype: int64



In [16]:

print(f"Сумма элементов: {s.sum()}")
print(f"Среднее значение: {s.mean()}\n")

Сумма элементов: 669
Среднее значение: 66.9



In [40]:

df = pd.DataFrame(np.random.randint(0, 100, size=(5, 4)), columns=list('ABCD'))
print(f"Объект Dataframe:\n{df}\n")

Объект Dataframe:
    A   B   C   D
0  66  16  54  75
1  58  28  13  18
2   9  47  89  89
3  66  53  48  13
4  45  72  50  96



In [34]:
df = df.drop(0)
print(f"Dataframe после удаления строки:\n{df}\n")

Dataframe после удаления строки:
    A   B   C   D
1  27  60  53  22
2  96  64   7  45
3  52  33  42  42
4  93  97  48  55



In [41]:
df = df.drop(columns='A')
print(f"Dataframe после удаления столбца:\n{df}\n")


Dataframe после удаления столбца:
    B   C   D
0  16  54  75
1  28  13  18
2  47  89  89
3  53  48  13
4  72  50  96



In [42]:
print(f"Размер Dataframe: {df.shape}\n")

Размер Dataframe: (5, 3)



In [43]:

values = (df == 6)
print(f"Элементы, равные 6:\n{values}\n")

Элементы, равные 6:
       B      C      D
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False



Объект Series:
0    79
1    99
2    65
3    63
4    20
5    44
6    84
7     6
8    35
9    97
dtype: int64

Сумма элементов: 592
Среднее значение: 59.2

Объект Dataframe:
    A   B   C   D
0  34  21  10   0
1   3  69  81  20
2  94  72  13  99
3  53   9   1  48
4  98   3  41  24

Dataframe после удаления строки:
    A   B   C   D
1   3  69  81  20
2  94  72  13  99
3  53   9   1  48
4  98   3  41  24

Dataframe после удаления столбца:
    B   C   D
1  69  81  20
2  72  13  99
3   9   1  48
4   3  41  24

Размер Dataframe: (4, 3)

Элементы, равные 6:
       B      C      D
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False

